keys:
  - &user_pinpox 3D65EA322A8D9D6FB657DF2EA5BCEFD22D30118A
  - &server_pretix age1spav05lfhsl0z4t2ds2sl8ncwxhdcq2e8t0ruwgzdm45xm2m8fvqmgwqkd
  - &user_manuliner age1uq7anatlkz8f343rqee9c93zwhhy6w75z0vfk2d8n30prmcufe5sg7a38s
    # = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICgmdQGbYprfoyrtNvgfrraaIco47J7NN+XoHXSSySSQ";
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *user_pinpox
      age:
      - *user_manuliner
      - *server_pretix
