keys:
  - &user_pinpox 3D65EA322A8D9D6FB657DF2EA5BCEFD22D30118A
  - &server_pretix age1spav05lfhsl0z4t2ds2sl8ncwxhdcq2e8t0ruwgzdm45xm2m8fvqmgwqkd
  - &user_manuliner age1r2nvjx5m4dq9hgakeuk9gcf6y37z3g5n87u3t4sh9ykzzk2dpg4qmrqxs8
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *user_pinpox
      age:
      - *user_manuliner
      - *server_pretix
